name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Show trigger event
        run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Show runner OS
        run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"

      - name: Show branch and repository
        run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Repository cloned
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Workflow ready
        run: echo "🖥️ The workflow is now ready to test your code on the runner."

      - name: List files in the repository
        run: |
          ls -la ${{ github.workspace }}

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Show job status
        run: echo "🍏 This job's status is ${{ job.status }}."
